# Generated by Django 5.1.6 on 2025-03-05 03:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Videogame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=5, max_digits=5)),
                ('release_date', models.DateField()),
                ('image', models.ImageField(upload_to='games/')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GameShop_app.genre')),
            ],
        ),
    ]
