# Generated by Django 5.1.6 on 2025-03-05 03:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GameShop_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название жанра'),
        ),
        migrations.AlterField(
            model_name='videogame',
            name='description',
            field=models.CharField(max_length=500, verbose_name='Описание игры'),
        ),
        migrations.AlterField(
            model_name='videogame',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GameShop_app.genre', verbose_name='Жанр игры'),
        ),
        migrations.AlterField(
            model_name='videogame',
            name='image',
            field=models.ImageField(upload_to='games/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='videogame',
            name='price',
            field=models.DecimalField(decimal_places=5, max_digits=5, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='videogame',
            name='release_date',
            field=models.DateField(verbose_name='Дата выхода'),
        ),
        migrations.AlterField(
            model_name='videogame',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название игры'),
        ),
    ]
