# Generated by Django 5.1.6 on 2025-03-05 03:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GameShop_app', '0002_alter_genre_name_alter_videogame_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Developers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название компаний разработчиков')),
            ],
        ),
        migrations.AddField(
            model_name='videogame',
            name='developers',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='GameShop_app.developers'),
        ),
    ]
