# Generated by Django 5.1.6 on 2025-03-05 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GameShop_app', '0004_alter_videogame_developers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Developers',
            new_name='Developer',
        ),
    ]
